CREATE DATABASE adatbazis CHARACTER SET 'utf8' COLLATE 'utf8_hungarian_ci';

USE adatbazis;

CREATE TABLE meals(id INT AUTO_INCREMENT PRIMARY KEY,
mealName VARCHAR(100) NOT NULL,
quantity INT NOT NULL,
price INT NOT NULL,
expiration DATETIME DEFAULT CURRENT_TIMESTAMP,
isSesonal BOOLEAN DEFAULT FALSE,
placeorigin VARCHAR(50),
mealDescription TEXT,
allergens JSON,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updateAt DATETIME DEFAULT CURRENT_TIMESTAMP);
 